USE J2EE3_DEMO
go

exec 	sp_adduser user1
exec 	sp_adduser user2
exec 	sp_adduser user3
exec 	sp_adduser user4
exec 	sp_adduser user5
exec 	sp_adduser user6
exec 	sp_adduser user7
exec 	sp_adduser user8
exec 	sp_adduser user9
exec 	sp_adduser user10
exec 	sp_adduser user11
exec 	sp_adduser user12
exec 	sp_adduser user13
exec 	sp_adduser user14
exec 	sp_adduser user15
exec 	sp_adduser user16
exec 	sp_adduser user17
exec 	sp_adduser user18
exec 	sp_adduser user19
exec 	sp_adduser user20
exec 	sp_adduser user21
exec 	sp_adduser user22
exec 	sp_adduser user23
exec 	sp_adduser user24
exec 	sp_adduser user25
exec 	sp_adduser user26
exec 	sp_adduser user27
exec 	sp_adduser user28
exec 	sp_adduser user29
exec 	sp_adduser user30
exec 	sp_adduser administrator
exec 	sp_adduser test

grant all to user1
grant all to user2
grant all to user3
grant all to user4
grant all to user5
grant all to user6
grant all to user7
grant all to user8
grant all to user9
grant all to user10
grant all to user11
grant all to user12
grant all to user13
grant all to user14
grant all to user15
grant all to user16
grant all to user17
grant all to user18
grant all to user19
grant all to user20
grant all to user21
grant all to user22
grant all to user23
grant all to user24
grant all to user25
grant all to user26
grant all to user27
grant all to user28
grant all to user29
grant all to user30
grant all to administrator
grant all to test